server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT → http://localhost:4004/api/patients
        ## API GATEWAY → http://patient-service:4000/patients
        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ## REST-CLIENT → http://localhost:4004/api-docs/patients
        ## API-GATEWAY → http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        ## REST-CLIENT → http://localhost:4004/swagger-ui/patients/**
        ## API-GATEWAY → http://patient-service:4000/swagger-ui/**
        - id: swagger-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/swagger-ui/patients/**
          filters:
            - RewritePath=/swagger-ui/patients/(?<segment>.*), /swagger-ui/${segment}

        ## REST-CLIENT → http://localhost:4004/auth/**
        ## API-GATEWAY → http://auth-service:4005/**
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters: 
            - StripPrefix=1

        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs
